package com.javarevolutions.siycp.ejb.entity;
// Generated 13/02/2014 04:39:40 PM by Hibernate Tools 3.6.0



/**
 * Inventarios generated by hbm2java
 */
public class Inventarios  implements java.io.Serializable {


     private Long idInventario;
     private Productos productos;
     private long cantidad;
     private Integer minimoExistencia;

    public Inventarios() {
    }

    public Inventarios(Productos productos, long cantidad) {
       this.productos = productos;
       this.cantidad = cantidad;
    }
   
    public Long getIdInventario() {
        return this.idInventario;
    }
    
    public void setIdInventario(Long idInventario) {
        this.idInventario = idInventario;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public long getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(long cantidad) {
        this.cantidad = cantidad;
    }

    /**
     * @return the minimoExistencia
     */
    public Integer getMinimoExistencia() {
        return minimoExistencia;
    }

    /**
     * @param minimoExistencia the minimoExistencia to set
     */
    public void setMinimoExistencia(Integer minimoExistencia) {
        this.minimoExistencia = minimoExistencia;
    }




}


