package com.javarevolutions.siycp.ejb.entity;
// Generated 13/02/2014 04:39:40 PM by Hibernate Tools 3.6.0



/**
 * PedidosProductos generated by hbm2java
 */
public class PedidosProductos  implements java.io.Serializable {


     private Long idPedidoProducto;
     private Pedidos pedidos;
     private Productos productos;
     private long cantidad;

    public PedidosProductos() {
    }

    public PedidosProductos(Pedidos pedidos, Productos productos, long cantidad) {
       this.pedidos = pedidos;
       this.productos = productos;
       this.cantidad = cantidad;
    }
   
    public Long getIdPedidoProducto() {
        return this.idPedidoProducto;
    }
    
    public void setIdPedidoProducto(Long idPedidoProducto) {
        this.idPedidoProducto = idPedidoProducto;
    }
    public Pedidos getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public long getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(long cantidad) {
        this.cantidad = cantidad;
    }




}


