package com.javarevolutions.siycp.ejb.entity;
// Generated 13/02/2014 04:39:40 PM by Hibernate Tools 3.6.0



/**
 * ProveedoresProductos generated by hbm2java
 */
public class ProveedoresProductos  implements java.io.Serializable {


     private Long idProveedorProducto;
     private Usuarios usuarios;
     private Productos productos;

    public ProveedoresProductos() {
    }

    public ProveedoresProductos(Usuarios usuarios, Productos productos) {
       this.usuarios = usuarios;
       this.productos = productos;
    }
   
    public Long getIdProveedorProducto() {
        return this.idProveedorProducto;
    }
    
    public void setIdProveedorProducto(Long idProveedorProducto) {
        this.idProveedorProducto = idProveedorProducto;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }




}


