package com.javarevolutions.siycp.ejb.entity;
// Generated 13/02/2014 04:39:40 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TiposMedidas generated by hbm2java
 */
public class TiposMedidas  implements java.io.Serializable {


     private Integer idTipoMedida;
     private String tipoMedida;
     private Set productoses = new HashSet(0);

    public TiposMedidas() {
    }

	
    public TiposMedidas(String tipoMedida) {
        this.tipoMedida = tipoMedida;
    }
    public TiposMedidas(String tipoMedida, Set productoses) {
       this.tipoMedida = tipoMedida;
       this.productoses = productoses;
    }
   
    public Integer getIdTipoMedida() {
        return this.idTipoMedida;
    }
    
    public void setIdTipoMedida(Integer idTipoMedida) {
        this.idTipoMedida = idTipoMedida;
    }
    public String getTipoMedida() {
        return this.tipoMedida;
    }
    
    public void setTipoMedida(String tipoMedida) {
        this.tipoMedida = tipoMedida;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


