package com.javarevolutions.siycp.ejb.entity;
// Generated 13/02/2014 04:39:40 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String user;
     private Usuarios usuarios;
     private String password;
     private Date fechaAcceso;
     private String statusUser;

    public Users() {
    }

    public Users(String user, Usuarios usuarios, String password, Date fechaAcceso) {
       this.user = user;
       this.usuarios = usuarios;
       this.password = password;
       this.fechaAcceso = fechaAcceso;
    }
   
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFechaAcceso() {
        return this.fechaAcceso;
    }
    
    public void setFechaAcceso(Date fechaAcceso) {
        this.fechaAcceso = fechaAcceso;
    }

    /**
     * @return the statusUser
     */
    public String getStatusUser() {
        return statusUser;
    }

    /**
     * @param statusUser the status to set
     */
    public void setStatusUser(String statusUser) {
        this.statusUser = statusUser;
    }




}


