package com.javarevolutions.siycp.ejb.entity;
// Generated 13/02/2014 04:39:40 PM by Hibernate Tools 3.6.0



/**
 * VentasProductos generated by hbm2java
 */
public class VentasProductos  implements java.io.Serializable {


     private long idVentaProducto;
     private Ventas ventas;
     private Productos productos;
     private long cantidad;

    public VentasProductos() {
    }

    public VentasProductos(long idVentaProducto, Ventas ventas, Productos productos, long cantidad) {
       this.idVentaProducto = idVentaProducto;
       this.ventas = ventas;
       this.productos = productos;
       this.cantidad = cantidad;
    }
   
    public long getIdVentaProducto() {
        return this.idVentaProducto;
    }
    
    public void setIdVentaProducto(long idVentaProducto) {
        this.idVentaProducto = idVentaProducto;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public long getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(long cantidad) {
        this.cantidad = cantidad;
    }




}


